/**
 * The step plan and the scope gate (M1-W3 / M1-W4).
 *
 * WHAT THIS FILE HAS TO PROVE, IN THE MILESTONE'S OWN WORDS
 * docs/06 §2.5's acceptance for 生成模式 is 「AI 采用结构化流程，不一次性生成全部」 and for 字段级 AI 操作 it
 * is 「选定字段可 AI 重写」 plus the scoping that makes it a feature. Both are statements about SHAPE, so
 * this file asserts shape rather than outcome:
 *   1. the plan is MORE THAN ONE step, its steps are DISJOINT, and every editable content field of the
 *      form is in exactly one of them — with the clock (calendar / pacing) in none;
 *   2. a step's scope is a strict subset of the card, and the instruction says which paths are in and
 *      which are out;
 *   3. the gate refuses an operation that leaves the scope, path by path — including the case a
 *      text-prefix comparison would get wrong (`/narrative/style` vs `/narrative/styles`);
 *   4. a field operation's plan is ONE step over ONE path, and its instruction carries the field.
 * The end-to-end sequence (more than one request, nothing touching every field) is asserted on the
 * wire in `state/co-create-store.test.ts`; this file pins the values that make that sequence possible.
 */
/** @vitest-environment node */
import { describe, expect, it } from 'vitest';
import { blankWorldData } from '../cards/world';
import { fieldOpRequest, fieldOpScope, readPath } from './field-ops';
import {
  fieldOpPlan,
  fieldSetPlan,
  PLAN_ID_FIELD_SET,
  PLAN_ID_WHOLE_CARD,
  stepScope,
  worldGenerationPlan,
} from './plan';
import { WORLD_PATCH_PATHS } from './proposal';
import { isPathWithin, scopeInstruction, scopePreamble, scopeVerdict } from './scope';

function world() {
  return { ...blankWorldData('霜月群岛'), premise: '群岛在霜月下沉' };
}

describe('the generation plan', () => {
  it('walks more than one step, and no step covers the whole card', () => {
    const plan = worldGenerationPlan();
    expect(plan.steps.length).toBeGreaterThan(1);
    const all = WORLD_PATCH_PATHS.map((entry) => entry.path);
    for (const step of plan.steps) {
      expect(step.paths.length).toBeGreaterThan(0);
      // 「不一次性生成全部」 starts here: no step's scope is the whole card, so no single request is
      // ever allowed to write every field.
      expect(step.paths.length).toBeLessThan(all.length);
    }
    // ...and the plan as a whole covers strictly fewer paths than the card has: the clock is not in it.
    expect(plan.paths.length).toBeLessThan(all.length);
  });

  it('gives every editable content field to exactly one step, and the clock to none', () => {
    const plan = worldGenerationPlan();
    const counts = new Map<string, number>();
    for (const step of plan.steps) {
      for (const path of step.paths) counts.set(path, (counts.get(path) ?? 0) + 1);
    }
    const content = plan.contentPaths;
    expect(content.length).toBeGreaterThan(0);
    for (const path of content) {
      expect(counts.get(path), `${path} is not generated by exactly one step`).toBe(1);
    }
    // The world's clock and pacing are the author's own, and no request may write them.
    for (const reserved of [
      '/calendar/minutesPerHour',
      '/calendar/months',
      '/startMinute',
      '/timeRhythm/stepMinutes',
    ]) {
      expect(counts.has(reserved)).toBe(false);
      expect(plan.reservedPaths).toContain(reserved);
    }
    // Every path the plan lists is a path the form actually offers (`proposal.ts` derives that list
    // from the editor's descriptor tables), so a step can never address a phantom field.
    const offered = new Set(WORLD_PATCH_PATHS.map((entry) => entry.path));
    for (const path of plan.paths) expect(offered.has(path)).toBe(true);
  });

  it('names each step from the plan order, and keeps the modes distinguishable', () => {
    const whole = worldGenerationPlan();
    expect(whole.id).toBe(PLAN_ID_WHOLE_CARD);
    expect(whole.steps.map((step) => step.id)).toEqual([
      'premise',
      'basics',
      'places',
      'powers',
      'rules',
      'narrative',
      'telling',
    ]);

    // 「逐字段生成」 is the SAME steps, chosen: a subset, in the plan's own order.
    const chosen = fieldSetPlan(['/rulesOfNature/taboos', '/premise', '/regions']);
    expect(chosen.id).toBe(PLAN_ID_FIELD_SET);
    expect(chosen.steps.map((step) => step.id)).toEqual(['premise', 'places', 'rules']);
    expect(fieldSetPlan(['/calendar/minutesPerHour']).steps).toEqual([]);
  });

  it('scopes one step to its own paths, and says which paths are not in it', () => {
    const plan = worldGenerationPlan();
    const premise = plan.steps[0];
    if (premise === undefined) throw new Error('the plan has no first step');
    const scope = stepScope(plan, premise, []);
    expect(scope.kind).toBe('generate-step');
    expect(scope.step).toBe('premise');
    expect(scope.paths).toEqual(['/premise']);

    const text = scopeInstruction(world(), scope);
    // In scope: the path and its label come from the form's own inventory.
    expect(text).toContain('- /premise  (world.premiseLabel)');
    // Out of scope: a later step, and the clock, are both named as untouchable.
    expect(text).toContain('DO NOT EDIT THESE PATHS IN THIS TURN');
    expect(text).toContain('- /era  (reserved for a later step of this generation)');
    expect(text).toContain('- /calendar/minutesPerHour  (a calendar or pacing setting');
    // The card itself is part of the instruction, so the model edits what the author is looking at.
    expect(text).toContain('"premise": "群岛在霜月下沉"');
    expect(text).toContain('THIS TURN GENERATES ONE STEP OF A CARD');
    // The plan is stated, so step 3 knows what step 1 and 2 settled.
    expect(scopePreamble(scope).join('\n')).toContain('THE PLAN FOR THIS CARD (7 steps, in order)');
  });
});

describe('the scope gate', () => {
  it('compares paths token by token, not as text', () => {
    expect(isPathWithin('/premise', '/premise')).toBe(true);
    expect(isPathWithin('/regions', '/regions/0/name')).toBe(true);
    expect(isPathWithin('/premise', '/premises')).toBe(false);
    // THE CASE A TEXT PREFIX GETS WRONG: `/narrative/style` is not a prefix of `/narrative/styles`,
    // and a scope on the first must not authorise a write to the second.
    expect(isPathWithin('/narrative/style', '/narrative/styles')).toBe(false);
    // An escaped token is one token on both sides (`a/b` is a customFields KEY, not a nesting).
    expect(isPathWithin('/customFields/a~1b', '/customFields/a~1b')).toBe(true);
    expect(isPathWithin('/customFields/a~1b', '/customFields/a/b')).toBe(false);
    expect(isPathWithin('', '/premise')).toBe(true);
  });

  it('refuses every operation that leaves the scope, and keeps the ones that do not', () => {
    const plan = worldGenerationPlan();
    const premise = plan.steps[0];
    if (premise === undefined) throw new Error('the plan has no first step');
    const scope = stepScope(plan, premise, []);
    const verdict = scopeVerdict(
      [
        { op: 'replace', path: '/premise', value: '新的一句' },
        { op: 'replace', path: '/era', value: '第三纪' },
      ],
      scope,
    );
    expect(verdict.inScope).toEqual([{ op: 'replace', path: '/premise', value: '新的一句' }]);
    expect(verdict.outOfScope).toEqual([{ op: 'replace', path: '/era', value: '第三纪' }]);
  });

  it('lets a step write inside the rows of the list it owns', () => {
    const plan = worldGenerationPlan();
    const places = plan.steps.find((step) => step.id === 'places');
    if (places === undefined) throw new Error('the plan has no places step');
    const scope = stepScope(plan, places, []);
    const verdict = scopeVerdict([{ op: 'add', path: '/regions/0/name', value: '霜月港' }], scope);
    expect(verdict.outOfScope).toEqual([]);
  });
});

describe('a field operation', () => {
  it('is one step over one path, whichever gesture it is', () => {
    for (const op of ['rewrite', 'expand', 'condense'] as const) {
      const { plan, step } = fieldOpRequest(['/rulesOfNature/taboos']);
      expect(plan.steps).toHaveLength(1);
      expect(step.paths).toEqual(['/rulesOfNature/taboos']);
      const scope = fieldOpScope(world(), '/rulesOfNature/taboos', op, ['/premise', '/era']);
      expect(scope.kind).toBe('field-op');
      expect(scope.fieldOp).toBe(op);
      expect(scope.paths).toEqual(['/rulesOfNature/taboos']);
      // Every other field of the card is named as untouchable, and the gesture is stated.
      expect(scope.excluded.map((entry) => entry.path)).toEqual(['/premise', '/era']);
      expect(scopePreamble(scope).join('\n')).toContain('/rulesOfNature/taboos');
    }
  });

  it('tells the model what the field currently says', () => {
    const scope = fieldOpScope(world(), '/premise', 'expand', []);
    const text = scopeInstruction(world(), scope);
    expect(text).toContain('THE FIELD AS IT STANDS: "群岛在霜月下沉"');
    expect(text).toContain('EXPAND this field');
    // A field that is not in the card yet is said to be absent rather than shown as an empty string:
    // a model about to rewrite it must not be told the field says nothing.
    const missing = fieldOpScope(world(), '/customFields/Weather', 'rewrite', []);
    expect(scopeInstruction(world(), missing)).toContain('does not exist in the card yet');
  });

  it('reads a nested payload value by its own path, and refuses a path that is not one', () => {
    const data = world();
    expect(readPath(data, 'premise')).toBe('群岛在霜月下沉');
    expect(readPath(data, 'rulesOfNature.taboos')).toBe('');
    expect(readPath(data, 'timeRhythm.stepMinutes')).toBe(60);
    expect(readPath(data, 'premise.deeper')).toBeUndefined();
    expect(readPath(data, 'notAField')).toBeUndefined();
  });

  it('refuses to build a plan for a path the form does not offer', () => {
    expect(() => fieldOpPlan(['/nope'])).toThrow(/not a field the form offers/);
  });
});
